apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  sources:
    - chart: base
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: "1.27.0"
      helm:
        releaseName: istio-base
    - chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: "1.27.0"
      helm:
        releaseName: istiod
        valuesObject:
          profile: ambient
    - chart: ztunnel
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: "1.27.0"
      helm:
        releaseName: ztunnel
    - chart: cni
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: "1.27.0"
      helm:
        releaseName: istio-cni
        valuesObject:
          profile: ambient
    - repoURL: https://github.com/Alt3rius/argo-rollouts-app.git
      targetRevision: HEAD
      path: istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jqPathExpressions:
        - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy